# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/davide/qt_ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MapPlotter import MapPlotter

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 900)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.endLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endLabel.sizePolicy().hasHeightForWidth())
        self.endLabel.setSizePolicy(sizePolicy)
        self.endLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.endLabel.setObjectName("endLabel")
        self.gridLayout.addWidget(self.endLabel, 1, 0, 1, 2)
        self.dstEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.dstEdit.setObjectName("dstEdit")
        self.gridLayout.addWidget(self.dstEdit, 1, 2, 1, 1)
        self.findPathBtn = QtWidgets.QPushButton(self.centralWidget)
        self.testBtn = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findPathBtn.sizePolicy().hasHeightForWidth())
        self.findPathBtn.setSizePolicy(sizePolicy)
        self.findPathBtn.setObjectName("findPathBtn")
        self.testBtn.setSizePolicy(sizePolicy)
        self.testBtn.setObjectName("testBtn")
        self.gridLayout.addWidget(self.findPathBtn, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.testBtn, 1, 3, 1, 1)
        self.sourceEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.sourceEdit.setObjectName("sourceEdit")
        self.gridLayout.addWidget(self.sourceEdit, 0, 2, 1, 1)
        self.startLabel = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startLabel.sizePolicy().hasHeightForWidth())
        self.startLabel.setSizePolicy(sizePolicy)
        self.startLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.startLabel.setObjectName("startLabel")
        self.gridLayout.addWidget(self.startLabel, 0, 0, 1, 2)
        self.statusConsole = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.statusConsole.setObjectName("statusConsole")
        self.gridLayout.addWidget(self.statusConsole, 2, 0, 1, 4)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.map = MapPlotter(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setObjectName("map")
        self.horizontalLayout.addWidget(self.map)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 829, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Heureka"))
        self.endLabel.setText(_translate("MainWindow", "End"))
        self.dstEdit.setText(_translate("MainWindow", "(65, 110)"))
        self.findPathBtn.setText(_translate("MainWindow", "Find Path"))
        self.testBtn.setText(_translate("MainWindow", "Exhaustive Test"))
        self.sourceEdit.setText(_translate("MainWindow", "(10, 70)"))
        self.startLabel.setText(_translate("MainWindow", "Start"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

